name: Weekly Indeed jobs report (chat only)

on:
  schedule:
    - cron: '0 18 * * TUE'   # 11:00 PT every Tuesday
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas requests
      - name: Run weekly report
        run: python jobs_report.py
